java dp_solver.DP_solver inputs/ais8.cnf > results_ais8.txt
java dp_solver.DP_solver inputs/coloring.cnf > results_coloring.txt
java dp_solver.DP_solver inputs/gs36.cnf > results_gs36.txt
java dp_solver.DP_solver inputs/h50.cnf > results_h50.txt
java dp_solver.DP_solver inputs/hole7.cnf > results_hole7.txt
java dp_solver.DP_solver inputs/hole8.cnf > results_hole8.txt
java dp_solver.DP_solver inputs/ii8a1.cnf > results_ii8a1.txt
java dp_solver.DP_solver inputs/s28.cnf > results_s28.txt
java dp_solver.DP_solver inputs/u32.cnf > results_u32.txt